### ISSUE TITLE
Zoom and then the circles disappear

### ISSUE THREAD

**Issue by dianaclem** [Chicago/opengrid#106]
Ran O'Hare and Midway on Samsung (both Firefox and Google).   It works fine.   I zoom in with my fingers and the polygon stays but the circles/points disappear.

![screenshot_2015-09-02-09-28-00 missing dots](https://cloud.githubusercontent.com/assets/12613503/9634152/01675fe0-5156-11e5-9141-a12e91ebd6e4.png)

**Comment by PriyaDoIT** [comment]
see if a leaflet upgrade is available and can clear this issue up.

**Comment by PriyaDoIT** [comment]
see #186 for another example of this

Hi @rladines has the leaflet already been upgraded?  I can't recreate this issue and I've tried testing this with a number of datasets now.

**Comment by rladines** [comment]
@PriyaDoIT and @reve0716 pls. confirm that this is no longer occurring with Leaflet 1.0.1. thanks

**Comment by PriyaDoIT** [comment]
I was not able to replicate the issue on INT.

**Comment by rladines** [comment]
Closing this since the missing-dots issue has not re-surfaced with the upgraded Leaflet lib.
