### ISSUE TITLE
Integrate remaining build processes

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/opengrid#117]
Travis-CI build automation was completed in #112. Need to implement automated Windows testing, check for package dependencies, and code coverage measures.

- [ ] Add code coverage using [Coveralls.io](www.coveralls.io)
- [ ] Use [David-DM](https://david-dm.org/) to check on NPM dependencies
- [ ] Add Windows testing using [AppVeyor](appveyor.com)

**Comment by rladines** [comment]
These are already configured.
