### ISSUE TITLE
Login page splash screen -- too big for mobile

### ISSUE THREAD

**Issue by dianaclem** [Chicago/opengrid#122]

**Comment by tomschenkjr** [comment]
I think this is done, right?

**Comment by dianaclem** [comment]
Yes.

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Mon, Jan 25, 2016 at 6:19 PM -0800, "Tom Schenk Jr" <notifications@github.com<mailto:notifications@github.com>> wrote:


I think this is done, right?

-
