### ISSUE TITLE
Filters with a space in the filter value produce an error

### ISSUE THREAD

**Issue by levyj** [Chicago/opengrid#129]
I have not fully vetted out when this error occurs but it appears that a rule where the FILTER VALUE contains a space produces the following:

Error: A general service exception has occurred.(Code: 0100)

This produces an error:
![image](https://cloud.githubusercontent.com/assets/5519959/12433417/91e619c0-bec6-11e5-86b4-f06b961eb102.png)

Filter values that do not include spaces, including those that replace the spaces with %20 work:
![image](https://cloud.githubusercontent.com/assets/5519959/12433406/7df4ece8-bec6-11e5-9d8b-ee7f734eb9ae.png)

**Comment by tomschenkjr** [comment]
Confirmed that I'm seeing the same thing
