### ISSUE TITLE
When the user declines geolocation and clicks the button again, they can't try to approve

### ISSUE THREAD

**Issue by stevevance** [Chicago/opengrid#131]
Steps to reproduce:
1. Click the GPS button
2. Decline the approval dialog box
3. Click the GPS button again
4. An ````alert()```` appears saying that the user declined to share location.

**Comment by tomschenkjr** [comment]
I think this is a browser restriction. For instance, checking [GrubHub](www.grubhub.com), the same actions will yield the same results. Refreshing still yields the same result.

Anyone have any example of otherwise?

**Comment by stevevance** [comment]
Got it. I didn't think it would be because I didn't tell the browser to refrain from asking in the future.
