### ISSUE TITLE
The "restaurants passing initial inspection" query shows things that aren't restaurants

### ISSUE THREAD

**Issue by stevevance** [Chicago/opengrid#133]
See the attached screenshot. The "restaurant" is a daycare that has a food preparation license. 
<img width="884" alt="screenshot 2016-01-19 19 00 57" src="https://cloud.githubusercontent.com/assets/1330459/12436931/091427c2-bedf-11e5-8cba-19f8d269ab6f.png">

**Comment by tomschenkjr** [comment]
Correct. Reviewing the query, it's missing the "facility_type" = "Restaurant" criteria.

Thanks.
