### ISSUE TITLE
Build status indicator broken?

### ISSUE THREAD

**Issue by Newman101** [Chicago/opengrid#137]
Hi. 

Build status indicators seem to be broken. View from my Google Chrome: 

![image](https://cloud.githubusercontent.com/assets/4118513/12453458/35e8aa28-bf8b-11e5-8adc-943f0f895a34.png)

**Comment by rladines** [comment]
Hi we're looking into this. We have noticed that this seems to regularly happen at a certain period in the day then resolves itself after that. Could be related to our use of shields.io links but not confirmed yet.

The build statuses are still "Passing" though if you click on the links.

**Comment by tomschenkjr** [comment]
We're going to stick with Shields.io for the moment. We're monitoring the related issue mentioned here.
