### ISSUE TITLE
Add a link to the source dataset

### ISSUE THREAD

**Issue by levyj** [Chicago/opengrid#140]
Unless there was an explicit design decision **not to** do this, consider adding the ability to open a dataset on the Data Portal in a separate tab or window.  There might be times someone wants to take a deeper dive into the source data or even just see the data as an aid to building a filter.

**Comment by tomschenkjr** [comment]
Similar to my other comment. The source would be Plenario in this case.


Tom Schenk Jr.

Chief Data Officer

Department of Innovation and Technology

City of Chicago

(312) 744-2770

tom.schenk@cityofchicago.org

data.cityofchicago.org


________________________________

**Comment by levyj** [comment]
Thanks.  As with the other issue (https://github.com/Chicago/opengrid/issues/143), https://github.com/UrbanCCD-UChicago/plenario/issues/203 may be relevant if accepted.
