### ISSUE TITLE
GetTheData link/button

### ISSUE THREAD

**Issue by jqnatividad** [Chicago/opengrid#144]
Ability to get the underlying data directly from the source, may it be CKAN, Socrata, etc.

https://github.com/BetaNYC/getDataButton

**Comment by tomschenkjr** [comment]
Right now, can download the data that is on the map using the icon below. The source data sets in these cases are on [Plenario](www.plenar.io)

![image](https://cloud.githubusercontent.com/assets/1639121/12457380/c95cad4e-bf69-11e5-84f9-25733a74435e.png)

**Comment by tomschenkjr** [comment]
@jqnatividad - just a quick follow-up to see if there was some other thoughts behind the "getDataButton" or if the export function gets to that aspect.
