### ISSUE TITLE
Add link to "help" on the toolbar

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/opengrid#150]

**Comment by rladines** [comment]
@tomschenkjr this actually made it as part of branch iss135 that was merged recently into the dev branch.

**Comment by tomschenkjr** [comment]
Ah, fantastic. Then we'll close this out when it's moved into `master`. Thanks for clarifying.


Tom Schenk Jr.

Chief Data Officer

Department of Innovation and Technology

City of Chicago

(312) 744-2770

tom.schenk@cityofchicago.org

data.cityofchicago.org


________________________________

**Comment by tomschenkjr** [comment]
Actually, I'm going to mark this as duplicated and close it. Reference back to #60. I'll close that as well, once we promote this to `master` branch.
