### ISSUE TITLE
chicago.opengrid.io/opengrid help link formatting is off

### ISSUE THREAD

**Issue by reve0716** [Chicago/opengrid#152]
The section in the help link under Pot Holes reported in 60602 is off and the title is spelled Pots Holes it should read (Pot Holes Reported in 60602). See Image below

![image](https://cloud.githubusercontent.com/assets/12734080/12861253/aa0393ac-cc27-11e5-8f88-aa8cc7a85e2d.png)

**Comment by PriyaDoIT** [comment]
closing this issue and @tomschenkjr will open a new issue.
