### ISSUE TITLE
Improve JSON Formatting in API Documentation

### ISSUE THREAD

**Issue by seancarroll** [Chicago/opengrid#160]
JSON formatting could use some love

**Comment by tomschenkjr** [comment]
Thanks @seancarroll. Do you have some specific items you were looking for but weren't documented as well?

**Comment by seancarroll** [comment]
JSON in https://opengrid.readthedocs.org/en/latest/OpenGrid%20API/ can be a wall of unformatted text that could use a bit of formatting to make it easier to understand the structure. Below is an example

<img width="742" alt="screen shot 2016-02-21 at 11 01 06 pm" src="https://cloud.githubusercontent.com/assets/1264419/13209953/aa9421cc-d8ef-11e5-864b-496c3b459218.png">

I think it would be helpful if it was formatted such as the following which I grabbed from http://docs.readthedocs.org/en/latest/api.html

<img width="691" alt="screen shot 2016-02-21 at 11 11 52 pm" src="https://cloud.githubusercontent.com/assets/1264419/13210046/b3906b2c-d8f0-11e5-8fc6-0989a488a142.png">

I've looked at mkdoc extensions as well as highlightjs but haven't been able to get the desired result yet.

**Comment by tomschenkjr** [comment]
Thanks!

**Comment by tomschenkjr** [comment]
@reve0716 - can you look at this and format the JSON? Swing by with any questions.

@rladines - FYI on this.

**Comment by reve0716** [comment]
I'm currently formatting the API document.
