### ISSUE TITLE
Show default radius or where radius should be chosen

### ISSUE THREAD

**Issue by smarziano** [Chicago/opengrid#161]
On both mobile and desktop devices there isn't a box or assistive text to indicate where radius can be chosen. This is inconsistent with the other Geo-spatial filter options such as "Within" and "Near." My assumption is that there is a default radius which should be shown.

Here is what it looks like on my desktop. The arrow is helpful in determining where to click.
![image](https://cloud.githubusercontent.com/assets/5550969/13410299/a4df6bfc-defc-11e5-943c-5bba0bd84c77.png)

Here is a screenshot of my iPhone 6, without an arrow or a default radius displayed it becomes very unclear where the user should choose a radius.
![img_4910](https://cloud.githubusercontent.com/assets/5550969/13410484/aadc5a64-defd-11e5-8b9e-1d824fe6e7ed.PNG)

**Comment by dianaclem** [comment]
I tried this on my iphone 6 on both Opengrid on the city network and on chicago.opengrid.io, and I couldn't reproduce the issue.  Whenever I use "Near", there is a list of parameters that defaults to the lowest level on the list, so it is always visible.   Here's a screenshot from OpenGrid.
![img_0835](https://cloud.githubusercontent.com/assets/12613503/13539370/9b4d92d2-e215-11e5-8e86-1773875a8c52.PNG)

**Comment by smarziano** [comment]
@dianaclem It seems like this is a specific problem with the "Potholes Near Me" commonly used query. 

This error does **not** occur with other "near me" queries such as "311 Service Requests around You" or "Open 311 Requests around you"

**Comment by tomschenkjr** [comment]
As discussed on [2016-03-18](https://github.com/Chicago/opengrid/wiki/OpenGrid-Weekly-Meeting-Notes-2016-03-18), this is being worked-on
