### ISSUE TITLE
Clarify Error: Radius data is not initialized

### ISSUE THREAD

**Issue by smarziano** [Chicago/opengrid#162]
I tried the search query "Potholes Near Me" while I was at my office (225 N Michigan Ave) and I received an error stating "Error: Radius data is not initialized." I was not clear what this meant. I **think** it means that there are no results within that certain radius. I am not sure what the radius is currently set at (this relates to #161) and it is difficult to determine how to quickly change the radius to get results.

This issue could be divided into two tasks: 1) clarification for the current error message, and 2) quick way to expand radius to find results.

**Comment by velocirabbit** [comment]
Are you still getting the error? What search field filters do you have set (on the right side of the page)?

**Comment by rladines** [comment]
Dup. See #161
