### ISSUE TITLE
No return result for an Address in the Quick Search Bar

### ISSUE THREAD

**Issue by reve0716** [Chicago/opengrid#163]
Typing an Address in the quick search bar will not return a query result; per Rod the issue has something to do with one of the parameters being sent to the Esri World Geocoder service. Below are the addresses I entered in the quick search bar:

Here are the address I tried running below:

222 S. Hamlin Chicago, Il
222 S Hamlin 
222 South Hamlin Chicago, Il
333 South State Street
333 S State Street Chicago, IL
50 W Washington 
50 E Washington
1 N Hamlin

**Comment by tomschenkjr** [comment]
@rladines - tested the fix and looks good.

**Comment by PriyaDoIT** [comment]
@tomschenkjr  looks like this issue was closed a week ago.  However, this issue still persists on both mobile and computer devices.

**Comment by tomschenkjr** [comment]
It was deployed in the last stable release of OpenGrid (https://github.com/Chicago/opengrid/releases/tag/v1.0.2), however, hasn’t been deployed to opengrid.io. Pinging @uturndata

We should cover this during the weekly meeting. I thought it was deployed (we covered it on 4/8: https://github.com/Chicago/opengrid/wiki/OpenGrid-Weekly-Meeting-Notes-2016-04-08#2-weekly-review-of-work-opengrid-v102), but my mistake for not confirming that in the next meeting.

**Comment by danxoneil** [comment]
Re: deploying to opengrid.io, @tomschenkjr: is there a timeline for moving this over to a City AWS instance? That would remove a dependency and take @uturndata out of the workflow.

**Comment by tomschenkjr** [comment]
Working with Amazon on this bit as part of moving a number of things over to AWS. Summer would be my current estimate as some of the team is going through workshops to skill-up.
