### ISSUE TITLE
Amazon Web Services Marketplace

### ISSUE THREAD

**Issue by ThomasGroch** [Chicago/opengrid#167]
Hello,
When OpenGrid will be available on Amazon Web Services Marketplace to deploy?

**Comment by tomschenkjr** [comment]
The application is currently being reviewed by Amazon's AWS team and hope to have it in the upcoming weeks.

/cc @nfspeedypur

**Comment by PriyaDoIT** [comment]
@thomasgroch OpenGrid is now available on AWS Marketplace here:
https://aws.amazon.com/marketplace/pp/B01EZ6YBTK
