### ISSUE TITLE
No datasets appear when trying to "Add dataset"

### ISSUE THREAD

**Issue by smarziano** [Chicago/opengrid#171]
When I clicked on "Add dataset," no datasets appeared in this list. This seems like a recent bug. 

![opengriderror-nodataset](https://cloud.githubusercontent.com/assets/5550969/14047025/44fb72fa-f273-11e5-9287-ac33a4160409.png)

**Comment by tomschenkjr** [comment]
Fixed for the time-being and discussed in the [weekly meeting](https://github.com/Chicago/opengrid/wiki/OpenGrid-Weekly-Meeting-Notes-2016-03-25#1-production-opengrid-issues). See #172 for follow-on
