### ISSUE TITLE
Better centering after queries

### ISSUE THREAD

**Issue by smarziano** [Chicago/opengrid#176]
When I make a search query, my results are partially covered up by the right query panel. I think centering of the map could be improved to work on more screen sizes. 

I am currently using a 13" Mac and here are a couple of examples of results:

<img width="1256" alt="screen shot 2016-04-07 at 9 45 49 pm" src="https://cloud.githubusercontent.com/assets/5550969/14372912/89e3a2c4-fd0a-11e5-9842-33c87488d7d6.png">

<img width="1253" alt="screen shot 2016-04-07 at 9 47 27 pm" src="https://cloud.githubusercontent.com/assets/5550969/14372951/f4eb77fe-fd0a-11e5-8bdf-092ea76af7ff.png">

**Comment by PriyaDoIT** [comment]
The map actually IS centered, however, the advanced search pane is covering up some of the results.  This issue will be handled in #232 and #223 .
