### ISSUE TITLE
Increase resilience Plenar.io back-end

### ISSUE THREAD

**Issue by Augustus2016** [Chicago/opengrid#181]
Enable Multi-AZ setup

**Comment by WillEngler** [comment]
Plenario's RDS Postgres instance is now Multi-AZ

<img width="1432" alt="screen shot 2016-04-14 at 3 01 42 pm" src="https://cloud.githubusercontent.com/assets/6283143/14543566/6709346c-025a-11e6-8647-dbc800a46875.png">

**Comment by Augustus2016** [comment]
Thanks Will!


Adam Dillman
Managing Partner
Uturn Data Solutions
adillman@uturndata.com
O 312-957-8532
M 773-895-1203
