### ISSUE TITLE
Increase resilience of Plenar.io web/API tier

### ISSUE THREAD

**Issue by Augustus2016** [Chicago/opengrid#182]

**Comment by PriyaDoIT** [comment]
Notes from April 2016 Meetings:
* The admin panel in Plenario would need to be moved to caching layer
* Would need to rework the Plenario deployment process
* It would need about 3 working days
- Will has completed preliminary work on this; config change is set to autoscale setup.  Until there is a need for this, he won't trigger it.
- This has been on Plenario's radar as a "nice to have"

**Comment by WillEngler** [comment]
Done! Plenario's API servers now live in an autoscaling group, managed with Elastic Beanstalk. We no longer manually manage any EC2 instances. Happily, this also means that much of our infrastructure config is now [under](https://github.com/UrbanCCD-UChicago/plenario/tree/master/.ebextensions) [version](https://github.com/UrbanCCD-UChicago/plenario/blob/master/cron.yaml) [control](https://github.com/UrbanCCD-UChicago/plenario/blob/master/plenario/settings.py). (If we wrote up some Cloud Formation that could spin up ElastiCache, RDS, and the worker and web Elastic Beanstalk environments, we'd be very close to plug and play.)

**Comment by Augustus2016** [comment]
Closing #182.  Thanks Will!
