### ISSUE TITLE
Geolocation error on Chrome: "Only secure origins are allowed"

### ISSUE THREAD

**Issue by smarziano** [Chicago/opengrid#183]
When using the "near me" filter, there is a geolocation error that comes up stating "Only secure origins are allowed." 

<img width="1257" alt="screen shot 2016-04-20 at 12 00 36 pm" src="https://cloud.githubusercontent.com/assets/5550969/14683405/32242578-06f0-11e6-9eed-7a017999331c.png">

The short link leads here: https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features

**Comment by tomschenkjr** [comment]
Thanks. What operating system are you using?

**Comment by smarziano** [comment]
Mac OSX 10.11.4
Chrome Version 50.0.2661.75 (64-bit)

**Comment by smarziano** [comment]
@nfspeedypur I am finding this issue on Windows, too.
![2016-04-22 14_11_24-opengrid](https://cloud.githubusercontent.com/assets/5550969/14752353/800283f2-0894-11e6-9411-f618c1ff96cc.png)

**Comment by tomschenkjr** [comment]
@rladines Is this part of or a consequence of #74?
