### ISSUE TITLE
Mobile>Advanced Search does not open on First try

### ISSUE THREAD

**Issue by PriyaDoIT** [Chicago/opengrid#184]
In the mobile version of the App, Advanced Search needs to be clicked on twice for it to open.
Devices: Nexus 5x, Samsung Galaxy, and Motorola Moto X Pure Edition, iPhone 6
Browser: Chrome on all devices.

This issue only occurs on the chicago.opengrid.io version, not on the city's OpenGrid test environment

**Comment by tomschenkjr** [comment]
Which device and browser did this appear to happen on?

**Comment by nfspeedypur** [comment]
Fixed in latest push
