### ISSUE TITLE
Update Advanced Search to support service-side geoSpatial filtering

### ISSUE THREAD

**Issue by rladines** [Chicago/opengrid#190]
This is for making the corresponding client-side changes to support the new new _/capabilities_ OpenGrid service resource and passing of geo-spatial filter to the service when the service supports the capability. (See Issue Chicago/opengrid-svc-template#3 for more details.)

**Comment by PriyaDoIT** [comment]
note from @rladines coding 100% complete, currently testing/debugging against sample opengrid_data - to be completed by end of day

**Comment by reve0716** [comment]
Completed
