### ISSUE TITLE
Plenar.io to support OR filters

### ISSUE THREAD

**Issue by PriyaDoIT** [Chicago/opengrid#197]
Currently Plenar.io does not support queries containing OR when attempting to filter a dataset.  This is not something that is configurable today.  To improve filtering capabilites,a possible solution would be for Plenar.io to act like mongo is it's backend and to make this a configurable feature.

**Comment by PriyaDoIT** [comment]
To @willengler

**Comment by tomschenkjr** [comment]
@PriyaDoIT - actually, can you close this and open this issue in Plenario's repo? https://github.com/UrbanCCD-UChicago/plenario/issues

**Comment by WillEngler** [comment]
I'll open it myself and tag the students who are working on it

**Comment by tomschenkjr** [comment]
:+1:

**Comment by WillEngler** [comment]
https://github.com/UrbanCCD-UChicago/plenario/issues/223

**Comment by PriyaDoIT** [comment]
Will has updated the API documentation for OR queries.  reopening this issue so we can update our documentation for chicago.opengrid.io
