### ISSUE TITLE
Test Login Screen Configuration

### ISSUE THREAD

**Issue by PriyaDoIT** [Chicago/opengrid#199]
UTURN currently disables the login screen.  In an effort to not have two separate code bases (opengrid.io and chicago.opengrid.io) we would need to test the admin functionality with the toggle off.  However, since chicago.opengrid.io is not connected to mongo, we are unable to test.  Need to see if UTURN can point to a JSON file in order to test.  They also need to work with EKI to learn how the admin functionality works.

**Comment by rladines** [comment]
@PriyaDoIT this can be closed, now integrated with release 1.3.0. Login can now be turned off/on through configuration
