### ISSUE TITLE
Table view is difficult to find

### ISSUE THREAD

**Issue by smarziano** [Chicago/opengrid#211]
This issue could be helped with pop-ups and a tour of the site (#138), but changing the color and making the arrow more prominent would help a lot. Currently, the color matches the browser color and the arrow is in the far corner. My recommendation is to make this bar a little larger, change it to a brighter color and put the arrow in the middle.

**Comment by PriyaDoIT** [comment]
Closing this issue since it is a duplicate of #138 .  Will add note about changing color and making arrow more prominent to 138.
