### ISSUE TITLE
More accessible language

### ISSUE THREAD

**Issue by smarziano** [Chicago/opengrid#216]
From the CUTGroup test, we saw that there are a lot of opportunities to make the language more accessible. On the homepage, we heard that a lot of the content seemed targeted to developers or the tech community. While on the advanced search, words like "geo-spatial filters" could be switched to "location" or "queries" could be switched to "searches." It would be worth going through the site again and noting words that could be switched to more accessible, plain-language options.

I would also think about the map markers, too, and making those easier to understand from a resident perspective.

**Comment by PriyaDoIT** [comment]
Change Datasets and Filters to Select Data
Change Additional/ Geo-Spatial Filters to Select Location
Change Advanced Search to Find Data
Change Quick Search to Find Places, Businesses, etc.
