### ISSUE TITLE
Improvements to design in showing selected items

### ISSUE THREAD

**Issue by smarziano** [Chicago/opengrid#217]
This relates to this issue: https://github.com/Chicago/opengrid/issues/177#issuecomment-226550570

There are opportunities throughout the site to match expectations when a feature is selected. For example, since the "Advanced Search" is open when you visit https://chicago.opengrid.io/opengrid/, the nav bar button should reflect it and be highlighted. 

Similarly, in the Advanced Search panel when the "Search" or "Manage Queries" is selected the text is white and the non-selected is a darker color. I would expect the darker color to be the one selected. To make this clearer, I might underline the selected option and switch those color choices.

**Comment by PriyaDoIT** [comment]
@rladines this is in reference to our discussion regarding the advanced search paneling and toggle.  (we will keep the adv search open by default).
