### ISSUE TITLE
Improve user initial experience: help docs and/or "?" button for query bar on right

### ISSUE THREAD

**Issue by bbrewington** [Chicago/opengrid#219]
I tried http://chicago.opengrid.io for the first time today, and I stumbled around the initial interface a bit, not sure how to get started....

Something that would be super helpful is to include a link to the End-User Documentation or some other kind of splash page(s) to walk the user through how to get started.  Also, maybe a "?" button like the quick search has?

We might end up using this in Atlanta!  Nice tool

**Comment by tomschenkjr** [comment]
@bbrewington - we missed following-up on this, but were able to get this launched. We will also be improving the documentation again with our next release.
