### ISSUE TITLE
Chicago.Opengrid.io should allow for "between" for date fields

### ISSUE THREAD

**Issue by dianaclem** [Chicago/opengrid#236]
For date fields, it is helpful to have "between" as an option.   Right now there is only greater and less than options.   Between is available in the OpenGrid code, but not available in Chicago.Opengrid.io.

Please review closed issue #147  and issues that were merged into that issue.   There had been issues with "between" and these have been resolved in regards to the inclusion of the dates specified.

**Comment by nfspeedypur** [comment]
Completed, pushed today.
