### ISSUE TITLE
Some of the API documentation is difficult to read

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/opengrid#241]
Some of the formatting is pretty difficult to read. See this example from http://opengrid.readthedocs.io/en/latest/OpenGrid%20API/#113-users
![image](https://cloud.githubusercontent.com/assets/1639121/17710675/e84bd7ae-63b3-11e6-8ba5-be76b81aa24c.png)

Might want to switch to a format like [this API docs](http://read-the-docs.readthedocs.io/en/latest/api.html#a-basic-api-client-using-slumber).

**Comment by seancarroll** [comment]
Currently a code block (<code></code>) is being used. Instead how about using '''json? Example provided below

```json
[
  {
    "id": "speed_camera_locations",
    "displayName": "Speed Camera Locations",
    "options": {
      "rendition": {
        "icon": "default",
        "color": "cyan",
        "fillColor": "#f03",
        "opacity": 80,
        "size": 10
      },
      "latLong": "latitude,longitude",
      "creationTimestamp": null,
      "defaultSort": null,
      "lat": "latitude",
      "long": "longitude"
  }
]
```

**Comment by seancarroll** [comment]
Just looked at the dev branch and it already has been updated to use ``` code fence
