### ISSUE TITLE
Color of dots not appearing correctly on opengrid.io

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/opengrid#245]
An odd bug on chicago.opengrid.io...

### Step 1

1. Go to chicago.opengrid.io and add a data set (i.e., 311 Service Requests - Abandoned Vehicles)
2. Add a second data set (i.e., Building Permits)
3. Choose a spatial boundary (i.e., Map Extent) and click submit.

Expectations: dots appear but should have different colors per #121
Result: dots appear are all the same color (see below), which does not align to expectations
![image](https://cloud.githubusercontent.com/assets/1639121/18413838/24011766-777b-11e6-9c31-0a3d15b03fd4.png)

### Step 2

1. Now, go to one of the data sets (i.e., Building Permits) and change the color to black
2. Execute the query

Expectations: Based on Step 1 (above), the Building Permits should now be black
Result: Only the line color for the dot is black (see below). The dot should be black, not just the line, so this does *not* align to expectations.
![image](https://cloud.githubusercontent.com/assets/1639121/18413851/87836ca8-777b-11e6-8e61-a7a141ae75c7.png)

### Step 3

1. Now, reduce the dot colors for Building Permits to Size 6.
2. Resubmit the query

Expectations: Based on Step 1 and 2, I'd expect the line color for the smaller dot should be black and also a smaller size.
Result: Aligns to expectations

/cc @uturndata

**Comment by nfspeedypur** [comment]
Completed. Pushed today.

**Comment by PriyaDoIT** [comment]
Based on testing on mobile. This issue still persists.

**Comment by reve0716** [comment]
Hi Priya,
![img_1710](https://cloud.githubusercontent.com/assets/12734080/18920941/99aadf56-8568-11e6-81ff-2fdcadc16d0c.PNG)

I've tested on both mobile and desktop and the colors for all data-sets are appearing in Red.

**Comment by nfspeedypur** [comment]
I took this as the circles were coming in as default as blue not the
expected red.

I will need to work on why the results are not getting a different color
automatically.

-David

**Comment by nfspeedypur** [comment]
I updated the service code to randomly assign a color to the dataset.  Since the datasets are not driven by a local DB I have no way to permanently tie the color to the dataset.

**Comment by PriyaDoIT** [comment]
Retested using Tom's steps and everything looks good.  Closing issue.
