### ISSUE TITLE
Ability to view data as a time series

### ISSUE THREAD

**Issue by PriyaDoIT** [Chicago/opengrid#252]
As a user, I would like to the ability to view data from a dataset as a time series.  Per our discussions regarding the West Nile Virus Data, it could be useful if the user could see this information as a line graph in the grid view>pie chart section.  The requirements in the context of West Nile Virus are:
- to view data over time for each trap id/location the data listed below
- perform arithmetic on another field besides trap id/trip/location (conditional sums).  This will require us to sum the number of mosquitoes and the number of mosquitoes positive for West Nile Virus by trap ID over time.  These will display as two different lines on the same chart.

The above requirements are written in the context of West Nile Virus, but we should be able to perform conditional sums for other data sets should this be requested.

**Comment by PriyaDoIT** [comment]
Per our discussions regarding this I started to put together the table below of how we can view data as a time series in OG/WG.  I started with the datasets in WG and for most of them we can just simply apply Counts of an event by date.  I think the two main things we should be able to configure at each dataset would be if we a.) need to count, sum, average, etc. and b.) what time frame to use (by day, month, quarter, week, year, etc).
For the datasets that don’t have a note next to them, I still need to think through once I have access to WG, but I think you can start to get the idea.
West Nile Virus is a special case since we are rolling up within the dataset.  See the excel file I sent via email.  The columns that I have highlighted in red are calculations using the raw data.
Please review this and let me know if you need any more information as I write up the requirements.
![image](https://cloud.githubusercontent.com/assets/18470113/20063963/992bfc06-a4ce-11e6-9d07-3a0a42fe6efb.png)

**Comment by dianaclem** [comment]
This should be tracked in Workfront as it is related only to WindyGrid.

I could reproduce it in INT.   Right now QA can’t reproduce it due to the other changes going on in there.

**Comment by PriyaDoIT** [comment]
@dianaclem what do you mean you can reproduce it in INT?  this is a new requirement for a future that hasn't been built yet?  I'll move this to WG.

**Comment by dianaclem** [comment]
Sorry ….I replied to the wrong one.   Should have been Regina’s issue with the Location getting errors.   Leave this one in OG

**Comment by PriyaDoIT** [comment]
Hello @rladines, per our meeting today we would like to have Group by None and the Line Graph appear as the default.  Thanks!
