### ISSUE TITLE
Quick Search Markers do not appear in INT

### ISSUE THREAD

**Issue by PriyaDoIT** [Chicago/opengrid#255]
WG INT environment I noticed that the quick search marker images do not appear.  

![image](https://cloud.githubusercontent.com/assets/18470113/19897638/c0b2aaba-a026-11e6-84ed-3e9caabcca20.png)

**Comment by rladines** [comment]
Fixed locally. Will schedule release of fix along with the others early next week.

**Comment by rladines** [comment]
Ready for re-test

**Comment by PriyaDoIT** [comment]
looks good on INT.  Test passed.

![image](https://cloud.githubusercontent.com/assets/18470113/20149559/74833e0a-a677-11e6-8e0a-5b6cff22164e.png)

**Comment by rladines** [comment]
Closing after @PriyaDoIT 's re-test
