### ISSUE TITLE
Searches near 'Me' and 'marker' are not working

### ISSUE THREAD

**Issue by rladines** [Chicago/opengrid#257]
report by @reve0716: searches using Location of Near "Me" and "marker" are getting an error "Cannot read property 'layerPointToLatLng' of undefined"

[priya]: this is happening in WG>INT environment

**Comment by rladines** [comment]
After researching on this, it was found that this is due to a reported issue with Leaflet 1.0, Leaflet/Leaflet#4978; will look into an alternative solution to get the geometry of the marker bounds

**Comment by PriyaDoIT** [comment]
related to #255

**Comment by rladines** [comment]
Was able to workaround the Leaflet issue by overriding the L.Circle behavior with 0.7.3's which was proven to work with our code. Will apply any future Leaflet patch later once this is fixed in their repo.

Read for re-test.

**Comment by PriyaDoIT** [comment]
Tested this issue on INT using both Marker and Around Me.  Passed.

**Comment by reve0716** [comment]
I completed the testing for markers and near me - Its a Go

**Comment by rladines** [comment]
Closing based on comments from @PriyaDoIT and @reve0716
