### ISSUE TITLE
To Large of an Area message when running a search

### ISSUE THREAD

**Issue by reve0716** [Chicago/opengrid#259]
I'm getting an error when using Location Community Area Loop or any other location. I have refreshed and cleared browser history i'm getting the same results. 

![image](https://cloud.githubusercontent.com/assets/12734080/20023992/73845c10-a2b1-11e6-933f-96597cabe6d2.png)

**Comment by PriyaDoIT** [comment]
@reve0716 what environment is this in?

**Comment by dianaclem** [comment]
I meant to respond to this one about tracking it in Workfront, but I did just try it in prod now that prod is back up.

It worked fine.    It doesn’t work in INT or QA right now because of the changes in there.

**Comment by reve0716** [comment]
confirmed production is back functioning properly cannot replicate the issue any longer in prod but remains the same in int.

**Comment by rladines** [comment]
Fixed, read for re-test

**Comment by PriyaDoIT** [comment]
@rladines I tried to rerun Regina's query in INT and it just times out with no messaging.

**Comment by rladines** [comment]
Closing this since the original issue has been resolved. We'll tackle the query error/timeout separately since that looks to be a service implementation-specific issue.
