### ISSUE TITLE
Remove Manage Queries in chicago.Opengrid.io

### ISSUE THREAD

**Issue by reve0716** [Chicago/opengrid#260]
We need to have the Manage Queries link removed from the Find Data Panel. It's confusing to an user and doesn't serve a purpose within the panel. Site: chicago.opengrid.io

**Current Image** 
![image](https://cloud.githubusercontent.com/assets/12734080/20066437/294abd6a-a4d7-11e6-9583-b2d98f01c8e7.png)

**How the panel should look after removal of the link**
![image](https://cloud.githubusercontent.com/assets/12734080/20066537/7e94e264-a4d7-11e6-9fe1-f12c2f9d3ae0.png)

**Comment by PriyaDoIT** [comment]
hi @rladines per pull request #274 commit summary I see you have --Added code to hide saved queries dropdown when autologin is on.  Can you confirm that this resolves this issue?

**Comment by rladines** [comment]
No, not the Manage Queries tab. The one that was fixed was hiding the "Load Saved queries" dropdown which became visible (when it should not have) on one of the builds.

**Comment by PriyaDoIT** [comment]
ok thanks for clarifying.  moving back to backlog.

**Comment by PriyaDoIT** [comment]
this can and will be handled in 1.3.1

**Comment by PriyaDoIT** [comment]
this can and will be handled in 1.3.1
