### ISSUE TITLE
Heat Map appears below dots

### ISSUE THREAD

**Issue by PriyaDoIT** [Chicago/opengrid#266]
![image](https://cloud.githubusercontent.com/assets/18470113/20156718/1fcb8fa0-a697-11e6-843c-70ada4189587.png)

![image](https://cloud.githubusercontent.com/assets/18470113/20156723/2621c5d6-a697-11e6-9159-e188d1503ad9.png)

**Comment by rladines** [comment]
Read for re-test in INT/QA

**Comment by PriyaDoIT** [comment]
Tested in INT - heat map now appears over dots.  Pass.

**Comment by rladines** [comment]
Closing per @PriyaDoIT 's comment above
