### ISSUE TITLE
Table Grid Hint and WG Logo as an active link

### ISSUE THREAD

**Issue by reve0716** [Chicago/opengrid#279]
For the table grid, I would like to have the hover over name change from Search Results to Table View Search Results or Table View Search.
This will be a helpful hint that it’s an actual table and there is data. Let me know what you all think.

![image](https://cloud.githubusercontent.com/assets/12734080/21462198/c58c2e32-c91e-11e6-80ba-b394697d05dc.png)

WindyGrid Logo needs to be an active link to the homepage

![image](https://cloud.githubusercontent.com/assets/12734080/21527645/3e0aaa10-ccf2-11e6-99f1-d780ac4f91b3.png)

**Comment by PriyaDoIT** [comment]
related to #138 Closing this issue
