### ISSUE TITLE
Production: Missing Data - Crimes

### ISSUE THREAD

**Issue by PriyaDoIT** [Chicago/opengrid#282]
the Crimes 2001- Present dataset is only showing data prior to date: 2016-12-27T23:49:00

![image](https://cloud.githubusercontent.com/assets/18470113/21686509/5282bbe2-d32b-11e6-81fb-e4cbc11c757b.png)

No data appears when filtering on Date between 12/28/2016 and today
![image](https://cloud.githubusercontent.com/assets/18470113/21686624/b71a593e-d32b-11e6-9da4-824f2438e684.png)

I tested other data sets and they are working fine. I also cross referenced the Crimes 2001- Present dataset in the [data portal ](https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2)and I see the most recent data is from 12/28/2016.

**Comment by reve0716** [comment]
**Opengrid.io Testing**

**Quick Search** 
When grid auto refreshes upon movement the data points changes colors – This actions happens only for Quick Search:
(business_licenses 60602 or 60624) and (business_licenses)
 Zooming in and out (using icons and mouse) or moving around the grid.

**Find Data Panel**
Crime with map Extent
Crime with no set boundary
When running a search in Find Data Panel… A total of 1000 points are not appearing on the grid, its cutting off sections where the map extent is trying to pull data and only displaying a handful of data points on the grid while the information box states that it’s a total of 1000 records on the grid. The behavior is off; the data is not centered on the map when plotting data on the grid. When I maneuver west or north on the grid the data doesn’t display within the map extent it displays at the bottom of it. It doesn’t show a total of 1000 data.
When I travel south on the grid the data seems fine and shows data points perceiving to add up to 1000 points. 

See Images below where data is at the bottom and a data bubble displays with no point on the grid. How the data differ in certain directions on the grid.

**Image One:**

![image](https://cloud.githubusercontent.com/assets/12734080/21690881/e9cf750c-d33b-11e6-89c5-fcad664ddcd5.png)

**Image Two:**

![image](https://cloud.githubusercontent.com/assets/12734080/21691294/8562eaac-d33d-11e6-8e15-444624626567.png)


Data points also disappears and reappears on the gird upon zooming in and out (This was a previous issue)

![image](https://cloud.githubusercontent.com/assets/12734080/21691423/1cc68b10-d33e-11e6-8a9b-4a2a93007528.png)

![image](https://cloud.githubusercontent.com/assets/12734080/21691457/385087dc-d33e-11e6-9fe4-fa0e5521a94e.png)

![image](https://cloud.githubusercontent.com/assets/12734080/21691478/4ca6a806-d33e-11e6-9667-2ea2a97baf88.png)

Data should be at the max of 1000 for Food Inspection Chicago
Food Inspection without boundary:
WHERE city in Chicago is only displaying 237 points on the grid
WHERE zip code in 60602 it displays 1000 data points

With No Filter returns 1000
With Map Extent returns 1000

Food Inspection with Map extent boundary:
WHERE city in Chicago is only displaying 31 points on the grid (165 with default map view)
WHERE zip code in 60602 it displays 1000 data points (with default view)

**Comment by PriyaDoIT** [comment]
Hi @reve0716 thanks for testing.  Could you open each as separate issues so we can better track them?  Thanks!

**Comment by levyj** [comment]
There is a seven-day lag before records appear in the crimes dataset.
