### ISSUE TITLE
Update User Docs

### ISSUE THREAD

**Issue by PriyaDoIT** [Chicago/opengrid#288]
Some notes from UTURN regarding documentation: 

I noticed the screenshots were from earlier versions with older images, not Mapbox.  Also, there is mention of saved queries, which are not available on the opengrid.io version.  Lastly, some of the filters that are available on Windygrid and are mentioned in the instructions are not available on opengrid.io.

This must be a result of having one set of user instructions for both windy grid and opengrid.io on read the docs. I’m thinking about the user experience for opengrid.io users who link to the read docs. It may be confusing since not all of that functionality is available.

**Comment by PriyaDoIT** [comment]
per our discussion, we will take the text from the Functional Design document, which is fully updated and paste it to the current User Documentation.  Going forward, Regina will update the User Documentation instead.

**Comment by reve0716** [comment]
The User Documentation has been updated
