### ISSUE TITLE
Crimes query returns Error code 0100

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/opengrid#291]
## Steps to reproduce:

1. Add dataset "Crimes - 2001 to Present"
2. Add a filter with the "date" column and choose any date
3. Click "Get Data"

## Result
User receives an error message:
```
A general service exception has occurred.(Code: 0100)
```

## Expected result:
Data returns

Issue was reported by a [user](https://twitter.com/Vincent_Messina/status/841379386532220929)

**Comment by nfspeedypur** [comment]
I have contacted the Plenar.io team because it does not look like the filtering is working for field type 'TIMESTAMP WITHOUT TIME ZONE', even on the Plenar.io site.

**Comment by nfspeedypur** [comment]
Jesse from Plenar.io fixed this issue on the Plenar.io side.  This is not working, without any changes, on Opengrid.io.
