### ISSUE TITLE
Detect and deal with changes in structure to current datasets

### ISSUE THREAD

**Issue by levyj** [Chicago/opengrid#292]
From time to time, the structure of a dataset will change. How can Open Grid find out about and deal with these changes?  This is related to the same issue in Plenario -- https://github.com/UrbanCCD-UChicago/plenario/issues/291.

**Comment by tomschenkjr** [comment]
@heyzoos - you mentioned this was deployed on Plenario now, right?

**Comment by HeyZoos** [comment]
@tomschenkjr - Yep, during the ETL process Plenario completely replaces the existing dataset instead of trying to perform upserts. This has been enough to ingest datasets where the number of columns changes.

**Comment by HeyZoos** [comment]
@tomschenkjr - However this does not address communicating the changes to Open Grid, the metadata about the dataset will change but that would have to actively be checked for.

**Comment by tomschenkjr** [comment]
@HeyZoos - great, and that does happen so closing the issue.
