### ISSUE TITLE
Calendar Cuts off when using greater than or less than

### ISSUE THREAD

**Issue by PriyaDoIT** [Chicago/opengrid#293]
![image](https://cloud.githubusercontent.com/assets/18470113/25091042/7ec97382-234c-11e7-80df-e406f8bb566f.png)

note: this does NOT happen in WindyGrid

**Comment by PriyaDoIT** [comment]
update from @rladines 

Looks to me like the calendar moves when one of the column names on the dropdown is long enough to push the operators to the next line. You might have to create an overriding CSS file to deal with something unique to the Plenario dataset. I think it is better this way than having to tweak the common CSS to accommodate implementation-specific stuff. Let me know your thoughts. It would be good to find something generic but I did not have a lot of time to investigate more.

**Comment by reve0716** [comment]
Retest this seems to be okay. Calendar appears when using greater than and less than.

**Comment by joollerer1** [comment]
Per 4/4/18 review, no longer an issue close item.
