### ISSUE TITLE
issue with displaying datasets

### ISSUE THREAD

**Issue by PriyaDoIT** [Chicago/opengrid#294]
Below is an issue submitted by an OG user via email.  Tom has requested Regina to look into this.

Hello, 

I don't know if this is a known bug or something new to report but every time I query results they don't display right away.  I have to zoom in and out couple of times before they display and when they do, it only displays the data on the bottom of the screen and ignores the rest of the map. I have to keep nudging the map past the bottom of the browser screen in order to display the new data points.

My explanation may not convey the bug behavior 100% but this is the best I can explain it.  Let me know if you have questions.

Thanks,
Zee

**Comment by nfspeedypur** [comment]
This is the drawing issue I was talking about a few weeks ago.  The belief
is that it is a bug with Leaflet.

-David

**Comment by PriyaDoIT** [comment]
hello @rladines does your work around that you implemented in WG address this issue?  I know this issue is a little different from the missing dots issue that I reported.

**Comment by PriyaDoIT** [comment]
update from @rladines 
The changes have been merged into dev; pls. take a look to see if this fixes the rendering issues with chicago.opengrid.io

Here’s the latest commit into dev:

https://github.com/Chicago/opengrid/commit/a2023ad9cc78105e4525a9d95b69e056bb8112f4

**Comment by PriyaDoIT** [comment]
@reve0716 has reached out to Zee for more details of the issue.

**Comment by reve0716** [comment]
Closing issue can't replicate.
No reply back from user.
