### ISSUE TITLE
Open Weather Layers not working

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/opengrid#301]
When clicking on an open weather layer, e.g., temperature, nothing appears to happen.

When I open the Javascript console in Chrome, I see there are several errors that `Failed to load resource: the server responded with a status of 401`. Below is a screenshot. 

Through experimentation, it's clear this is related to anytime an open weather map layer is chosen. 

![image](https://user-images.githubusercontent.com/1639121/26902613-8e5fd522-4b9f-11e7-9d49-3ee6b38bc792.png)

**Comment by nfspeedypur** [comment]
I just took a look into this and I am seeing a 404 error when we try to hit the map images.

![image](https://user-images.githubusercontent.com/12736635/26910797-c3c12e6c-4bce-11e7-85d7-0befba8d8665.png)

This all still works on WindyGrid correct?

**Comment by nfspeedypur** [comment]
Could these APIs have changed?  From what I see on OpenWeatherMap.org the url requires an API key which we do not have in the project.

API Details - https://openweathermap.org/api/weathermaps

**Comment by tomschenkjr** [comment]
It's an issue in WindyGrid, too.

You beat me to it (was just looking at the code) -- I think that's what changed, the required API key. We'll get one of those and add it.

**Comment by tomschenkjr** [comment]
@nfspeedypur - I've registered an API key and will email it to you.

Right now, it's limited to 60 calls per hour. We'll see if we hit that limit very much.

**Comment by tomschenkjr** [comment]
Still appears to have an issue with "Cloud Cover"

**Comment by nfspeedypur** [comment]
When I go onto OpenWeatherMap.org the cloud map looks hard to really see a
difference.  Could there be an issue with the transparency?

-David

**Comment by tomschenkjr** [comment]
Don't think that's the issue in this case. I had spotted errors, 404, in the console when trying to load cloud cover. The rest of the layers work, though.

**Comment by nfspeedypur** [comment]
Tom/Rod,

Can you guys check to see if this API is similar to what you guys are using on WindyGrid? Removed the beginning of the APPID

http://a.tile.openweathermap.org/clouds/14/4202/6088.png?APPID=XXXXXXXXXXXXXXXXXafe

-David

**Comment by rladines** [comment]
This is what we have on WindyGrid. Looks like we're missing the /map/ portion of the URL. Sorry, I missed this when I updated the APPIDs on the OpenGrid side.
http://{s}.tile.openweathermap.org/**map**/clouds/{z}/{x}/{y}.png?APPID=XXXXXXXXXXXXXXX

@nfspeedypur feel free to update the URL

**Comment by nfspeedypur** [comment]
I will add this to the next release.

**Comment by tomschenkjr** [comment]
Thanks, so this will be added with the 1.4.3 release?

**Comment by reve0716** [comment]
@nfspeedypur the updates for opengrid for this issue has been push over to production; when I tested the weather layers I m still seeing the same behavior for the cloud coverage.

**Comment by nfspeedypur** [comment]
Regina,

The code was merged to production OpenGrid this past weekend.  I will be
making a new release from the Smart Chicago repo in the next day.

Thanks,
David Matthews

**Comment by nfspeedypur** [comment]
This code has been released to production.

-David

**Comment by reve0716** [comment]
Thanks @nfspeedypur  I've completed testing in OG, cloud coverage is functioning properly.

![image](https://user-images.githubusercontent.com/12734080/32807529-c4d90784-c955-11e7-8274-95740a43df7c.png)
