### ISSUE TITLE
Create release for v1.4.0

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/opengrid#305]
Need to publish a [release](https://github.com/Chicago/opengrid/releases) that summarizes the changes for v1.4.0. Below is my initial draft:

```
New Features:
* Added a time-series and bar-chart to view data over time (#252)
* Support for bubble plots, where the dots are sized based on data (#239)
* Support for displaying "array" data in the grid/table. Only supported with the MongoDB service layer and is not on opengrid.io. (#235)
* Share queries by copying and pasting the URL (#115)

Bug fixes:
* ... ?

API 
* ...?

Configuration and Administration
* ...?
```

@rladines - can you fill in any of these gaps? Thanks.

**Comment by rladines** [comment]
@tomschenkjr See my additions below:

New Features:
* Added a time-series and bar-chart to view data over time (#252)
* Support for bubble plots, where the dots are sized based on data (#239)
* Support for displaying "array" data in the grid/table. Only supported with the MongoDB service layer and is not on opengrid.io. (#235)
* Share queries by copying and pasting the URL (#115)
```diff
+* Support for custom date format on grid/table for date fields
````
Bug fixes:
```diff
+*None
````

API 
```diff
+* A new chart object is now returned as part of the dataset descriptor under the option object
+* New column attributes were added to support #239 and #115, respectively: "dotSizer"; and "array"
````

Configuration and Administration
```diff
+None
````

**Comment by tomschenkjr** [comment]
Thank you, release has been [created](https://github.com/Chicago/opengrid/releases/tag/v1.4.0).
