### ISSUE TITLE
OpenGrid not displaying recent Transportation Permits

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/opengrid#308]
@levyj reported a query showing [transportation permits on OpenGrid](https://chicago.opengrid.io/opengrid/#/query?q=%7B%22name%22:%22%22,%22owner%22:%22NoAuth%22,%22spec%22:%5B%7B%22dataSetId%22:%22transportation_department_permits%22,%22filters%22:%7B%22condition%22:%22AND%22,%22rules%22:%5B%7B%22id%22:%22streetclosure%22,%22field%22:%22streetclosure%22,%22type%22:%22string%22,%22input%22:%22text%22,%22operator%22:%22in%22,%22value%22:%22Curblane,Full,Partial,Intermitte%22%7D%5D%7D,%22rendition%22:%7B%22color%22:%22%2523CD5C5C%22,%22opacity%22:%2280%22,%22size%22:%226%22%7D%7D%5D,%22sharedWith%22:%7B%22users%22:%5B%5D,%22groups%22:%5B%5D%7D,%22isCommon%22:false,%22autoRefresh%22:false,%22refreshInterval%22:%2230%22,%22geoFilter%22:%7B%22boundaryType%22:%22within%22,%22boundary%22:%22_drawn-extent%22,%22value%22:%7B%22type%22:%22FeatureCollection%22,%22features%22:%5B%7B%22type%22:%22Feature%22,%22properties%22:%7B%7D,%22geometry%22:%7B%22type%22:%22Polygon%22,%22coordinates%22:%5B%5B%5B-87.74745941162111,41.96076659058398%5D,%5B-87.74745941162111,41.96076659058398%5D,%5B-87.7277183532715,41.96098997399536%5D,%5B-87.7277183532715,41.96098997399536%5D,%5B-87.72741794586183,41.94634074677108%5D,%5B-87.72741794586183,41.94634074677108%5D,%5B-87.73883342742921,41.94621306986162%5D,%5B-87.73883342742921,41.94621306986162%5D,%5B-87.74745941162111,41.96076659058398%5D%5D%5D%7D%7D%5D%7D%7D%7D&run=true&_=1497184090851) is not showing Application Number `DOT823426` that's [available on the open data portal](https://data.cityofchicago.org/Transportation/Transportation-Department-Permits/pubx-yq2d/data). Moreover, OpenGrid does not appear to be showing any data from 2017.

To narrow the issue to either Plenario or OpenGrid, I've compared [data from 2017-01-01 to 2017-07-05 on Plenario](http://plenar.io/v1/api/detail?agg=week&resolution=500&obs_date__le=2017-07-05&obs_date__ge=2017-01-01&dataset_name=transportation_department_permits&data_type=geojson) to the [same filter criteria on the open data portal](https://data.cityofchicago.org/resource/pubx-yq2d.json?$where=applicationstartdate%20%3E=%20%222017-01-01%22%20AND%20applicationstartdate%20%3C=%20%222017-07-05%22) and it appears Plenario is not loading the data.

@HeyZoos - do you know if there have been ETL failures bringing-in that data?

**Comment by HeyZoos** [comment]
Hi Tom, it looks like there are ETL failures happening - I'm currently debugging the issue and I'll let you know when I have it re-ingested.

**Comment by tomschenkjr** [comment]
Thanks!

_
Tom Schenk Jr.
Chief Data Officer
Department of Innovation and Technology
City of Chicago
(312) 744-2770
tom.schenk@cityofchicago.org | @ChicagoCDO
data.cityofchicago.org | opengrid.io | digital.cityofchicago.org | chicago.github.io | dev.cityofchicago.org


________________________________
