### ISSUE TITLE
Table Grid Information not displaying for POI Searches and Address Searches when running a Quick Search

### ISSUE THREAD

**Issue by reve0716** [Chicago/opengrid#321]
Table does not appear in POI search also error message appears below.

![ogqs](https://user-images.githubusercontent.com/12734080/29929863-57d4c2da-8e32-11e7-8802-53a4f214230f.png)

**Comment by tomschenkjr** [comment]
@reve0716 - can you open an SMS ticket on this? Thanks.

**Comment by reve0716** [comment]
@nfspeedypur  There was issue awhile back where the Quick Search address and place searches were returning an error message of: No creation Time Stamp, I know it was fixed in WindyGrid was the same fixed implemented in OpenGrid? 

![image](https://user-images.githubusercontent.com/12734080/35741243-eb1e317c-07fc-11e8-9385-8b6a3a32794b.png)

**Comment by nfspeedypur** [comment]
The Windygrid change was merged in and release.  However it does not look
like it is working.  I can work on troubleshooting this issue and see about
getting a new patch out there.

-David

**Comment by reve0716** [comment]
@nfspeedypur Ok, thanks

**Comment by nfspeedypur** [comment]
![image](https://user-images.githubusercontent.com/12736635/36104905-dde85990-0fd8-11e8-81db-15269c1835e0.png)

I have fixed this issue.  I am not sure how, but it seems like 1 of the last check ins never made it to the OpenGrid release.  This has been updated.

**Comment by tomschenkjr** [comment]
Thanks. For clarification, were the changes on the `master` branch of Chicago/opengrid or did you have to make a local change?

That is, do we need to update the main branch of opengrid?

**Comment by nfspeedypur** [comment]
No update is needed. The code change Rod made last fall fixed the issue and
the code merge into SmarChicago Repo worked. However the odd part is that
when I pulled down the repo to release the code in November I only got 1 of
the 2 changes. I am not sure if there was a file conflict that caused it,
but I was able to pull down the change on Monday and pushed out the code.

-David

**Comment by tomschenkjr** [comment]
Thanks.

@reve0716 - please check this as well and close the issue if you agree that it's been fixed.

**Comment by reve0716** [comment]
Testing has been completed.
