### ISSUE TITLE
Select Location is hidden but defaults to Map Extent

### ISSUE THREAD

**Issue by levyj** [Chicago/opengrid#322]
I am not sure if this is new or I just never noticed before but it looks as if Select Location in Search defaults to **Map Extent** instead of **SELECT BOUNDARY** or **Citywide**. However, this selection is hidden by default. That can produce the effect of returning no records, even though the user is not knowingly doing a geographic restriction.

![image](https://user-images.githubusercontent.com/5519959/30876567-9e999332-a2bc-11e7-90ed-31a850859769.png)

![image](https://user-images.githubusercontent.com/5519959/30876585-aedcaf9a-a2bc-11e7-9455-048c962320d9.png)

**Comment by tomschenkjr** [comment]
Yeah, this was a deliberate choice in [v1.2.0](https://github.com/Chicago/opengrid/releases/tag/v1.2.0). After the CUTGroup, we realized that users often would use the map extent to navigate to a section to conduct a search. Likewise, after looking at other maps (e.g., Google Maps), we found they also used map extent as the search mechanism.

**Comment by tomschenkjr** [comment]
Also, was you move the map it will auto-refresh so if you pan across, the data will update.

**Comment by levyj** [comment]
Fair enough if it was intentional.  I know well that nothing is intuitive to everyone.

That said, I am not sure panning necessarily helps if the person interprets the initial response as saying that no matching records exist.

Out of curiosity, I just checked Google Maps. It is right that if there are matching records with my extent it shows only them (sort of since the list does give me some access to other results).

![image](https://user-images.githubusercontent.com/5519959/30877210-a5b661f2-a2be-11e7-8bc7-40567689baa4.png)

 However, if there are no matching results in the extent, it will zoom out a lot to find me some.

![image](https://user-images.githubusercontent.com/5519959/30877266-cadd4108-a2be-11e7-98c6-1dacc98390b2.png)

**Comment by levyj** [comment]
Not to bury my point, though. One can always nit-pick so since this was intentional, I am not now asking for a change. Thanks.

**Comment by tomschenkjr** [comment]
No problem.
