### ISSUE TITLE
Deactivate ads for Mkdocs

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/opengrid#331]
MkDocs [has noted that they will be expanding advertisements on their documentation pages](https://blog.readthedocs.com/ads-on-other-themes/). Soon, they will be display ads on our documentation for OpenGrid.

However, you can opt out. @reve0716 - please [read this](http://docs.readthedocs.io/en/latest/ethical-advertising.html#opting-out) and deactivate ads for OpenGrid.

@joollerer1 - please add this to the weekly agenda for tracking.

**Comment by reve0716** [comment]
I opt out of seeing user paid advertisements and on the project level there are three options offered:

- Supporting us financially with Read the Docs Gold. This will disable all ads from showing on your project’s documentation.
- Supporting us with your time by contributing to the project.
- Moving to our paid product over at readthedocs.com.

I Opt out without doing any of the above by deselecting the option to Allow Paid Advertising.
