### ISSUE TITLE
Opengrid Documentation Site is Broken

### ISSUE THREAD

**Issue by reve0716** [Chicago/opengrid#338]
The opengrid.io documentation site under read the docs is broken. There is an 404 Error 

![image](https://user-images.githubusercontent.com/12734080/56507875-64551a80-64e8-11e9-9868-7bd39ec4068b.png)

Reference from issue #337

**Comment by rladines** [comment]
@reve0716 the link used to work on an old version. See below: 
https://docs.opengrid.io/en/stable/User%20Documentation/

But this appears to be invalid now with the latest

**Comment by reve0716** [comment]
@rladines  I created an SMS Ticket [12134](https://chicagogov.sharepoint.com/sites/SMS/_layouts/15/FormServer.aspx?XmlLocation=/sites/SMS/Change/CR_20190425151541.xml&Source=https://chicagogov.sharepoint.com/sites/SMS/SiteAssets/sms/views/sms/closeform.aspx) for tracking.

**Comment by reve0716** [comment]
Rod talk with patrick he's trying to get an access key, more updates will be provided.

**Comment by rladines** [comment]
@reve0716 Can you confirm if this the correct URL? http://docs.opengrid.io/en/latest/

**Comment by reve0716** [comment]
@rladines yes, this is the correct URL

**Comment by rladines** [comment]
@reve0716 The help link is fixed now. Check it out.

**Comment by reve0716** [comment]
@the link is currently in functioning retested today.
