### ISSUE TITLE
Open weather layers

### ISSUE THREAD

**Issue by reve0716** [Chicago/opengrid#343]
Weather layers on the map are returning 401 unauthorzed error/ fail to load resource.

![image](https://user-images.githubusercontent.com/12734080/59218941-fbecf600-8b86-11e9-9b9a-9426f4445967.png)

**Comment by rladines** [comment]
@reve0716 Try this again. The OpenWeather 401s should be resolved now

**Comment by reve0716** [comment]
@rladines Thanks, tested it and OWL are functioning properly.
Closing Issue
