### ISSUE TITLE
•	Ability to move the columns 

### ISSUE THREAD

**Issue by dianaclem** [Chicago/opengrid#55]
Be able to move the columns in the grid.   Needs more testing

**Comment by tomschenkjr** [comment]
This is done, right?

**Comment by tomschenkjr** [comment]
@dianaclem - forgot to mention this during the meeting today. There wasn't anything else to this, right?

**Comment by dianaclem** [comment]
It is a duplicate to #52. Documented above as such.  That's why I closed it.   You reopened it.
