### ISSUE TITLE
IE compatibility issues

### ISSUE THREAD

**Issue by dianaclem** [Chicago/opengrid#68]
Having launch issues with both IE8 and IE11.   Rod thought it might be the security tokens, so logging this ticket.

**Comment by tomschenkjr** [comment]
Notwithstanding #126, we're good with IE10 and IE11, right?

**Comment by dianaclem** [comment]
Yes.   We have not tested Edge/ie12.

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Wed, Feb 3, 2016 at 4:27 PM -0800, "Tom Schenk Jr" <notifications@github.com<mailto:notifications@github.com>> wrote:


Notwithstanding #126<https://github.com/Chicago/opengrid/issues/126>, we're good with IE10 and IE11, right?

-
